### ISSUE TITLE
Connections across WAN

### ISSUE THREAD

**Issue by genecyber** [m-onz/hyperdb-mesh#3]
Is there some magic to making this work across networks? On the same network this works, but once I've got a peer on another network, a connection isn't made (db.watch never fires and no records are added)

**Comment by m-onz** [comment]
I hope it works!! I have been trying out some stuff using this library with nodes in different continents and it seemed to work fine. Can you set up nodes in a VPS or get an error / issue and I will try and help you figure out what's going on.

**Comment by m-onz** [comment]
the authorization between peers needs to be successful for you to .watch for events.

**Comment by m-onz** [comment]
brilliant! Glad to hear your ok! I was planning to add some more authentication but I hadn't figured it out. The systems I'm working on for fun don't actually trust the entire data base and use encryption to allow only one peer (me) to read all the data so I don't really care about that problem.

I do want to add something to the library to make the mesh more secure... i had the idea of mesh groups that update and can drop bad peers from the group.
